# Linear Algebra

## Vector  arithmetics

In [11]:
import numpy as np
a=np.array([20,40,60])
b=np.array([10,70,60])
c=np.array([80,90,100])


In [13]:
#vector addition
a+b

array([ 30, 110, 120])

In [15]:
a+c


array([100, 130, 160])

In [17]:
#vector subtraction
a-b

array([ 10, -30,   0])

In [19]:
#vector multiplication
a*b

array([ 200, 2800, 3600])

In [21]:
#vector division
b/c

array([0.125     , 0.77777778, 0.6       ])

In [23]:
a=np.array([20,40,60])
c=np.array([80,90,100,40])
a+c #cuz different shapes

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [25]:
scalar=2

In [27]:

list_a=[10,11,12,13,14,15]
print(list_a)

[10, 11, 12, 13, 14, 15]


In [29]:
list_as_array=np.array(list_a)
print(list_as_array)

[10 11 12 13 14 15]


In [31]:
scalar*list_a

[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15]

In [33]:
scalar*list_as_array

array([20, 22, 24, 26, 28, 30])

In [35]:
a=np.array([20,40,60])
b=np.array([10,70,60])
c=np.array([80,90,100])

In [37]:
np.dot(a,b)


6600

In [39]:
np.dot(b,a)

6600

In [41]:
np.dot(c,a)

11200

In [43]:
first_result=np.dot(a,b+c)
print(first_result)

17800


In [45]:
second_result=np.dot(a,b)+ np.dot(a,c)
print(second_result)

17800


In [47]:
import numpy as np

a = np.array([3, 4])
b = np.array([1, 0])

# Scalar projection
scalar_proj = np.dot(a, b) / np.linalg.norm(b)

# Vector projection
vector_proj = (np.dot(a, b) / np.dot(b, b)) * b

print("Scalar projection:", scalar_proj)
print("Vector projection:", vector_proj)


Scalar projection: 3.0
Vector projection: [3. 0.]


In [49]:
magnitude = np.linalg.norm(a)
print(magnitude)

5.0


In [51]:

a = np.array([1, 2])
b = np.array([-2, 1])

dot = np.dot(a, b)  # (1)(-2) + (2)(1) = -2 + 2 = 0

print("Dot product:", dot)

if dot == 0:
    print("Vectors a and b are orthogonal")


Dot product: 0
Vectors a and b are orthogonal


In [53]:
#Matrix Multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.dot(A, B)  # or A @ B

print("Matrix composition (A × B):")
print(C)


Matrix composition (A × B):
[[19 22]
 [43 50]]


In [55]:
A = np.array([[2, 0],
              [0, 3]])

A_squared = np.dot(A, A)  # Or A @ A

print("A squared (A composed with A):")
print(A_squared)


A squared (A composed with A):
[[4 0]
 [0 9]]


In [57]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.array([[1],
              [0]])

# Step 1: A @ B
AB = A @ B

# Step 2: (AB) @ C
ABC = AB @ C

print("A · B · C =")
print(ABC)


A · B · C =
[[ 58]
 [139]]


In [59]:
#Gaussian Elimination, one of the most important techniques to solve systems of linear equations using Linear Algebra.
# Coefficient matrix
A = np.array([[1, 1, 1],
              [2, 3, 7],
              [3, 4, 10]])

# Constants (right-hand side)
b = np.array([6, 20, 28])

# Solve using numpy
x = np.linalg.solve(A, b)

print("Solution [x, y, z]:", x)


Solution [x, y, z]: [2. 3. 1.]


In [61]:
print(A)

[[ 1  1  1]
 [ 2  3  7]
 [ 3  4 10]]


In [63]:
# Matrix with a zero pivot at top
A = np.array([[0, 1],
              [1, 1]], dtype=float)
b = np.array([1, 2], dtype=float)

# Step 1: Pivot - Swap row 0 and row 1
A[[0, 1]] = A[[1, 0]]
b[[0, 1]] = b[[1, 0]]

# Now proceed with elimination
x = np.linalg.solve(A, b)
print("Solution:", x)


Solution: [1. 1.]


In [65]:
#INVERSION MATRIX
A = np.array([[4, 7], [2, 6]])
B = np.array([10, 8])  # Vector on the right-hand side

# Solve using inverse
A_inv = np.linalg.inv(A)
x = A_inv @ B

print("Solution x =", x)


Solution x = [0.4 1.2]


In [67]:
#determinant of matrix
# 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])

# 3x3 matrix
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

det_A = np.linalg.det(A)
det_B = np.linalg.det(B)

print("Determinant of A =", det_A)
print("Determinant of B =", det_B)


Determinant of A = 10.000000000000002
Determinant of B = 0.9999999999999987


In [69]:
#change of basis

v = np.array([5, 3])
B = np.array([[1, -1],
              [1, 2]])

# New coordinates of v in the new basis
v_new_basis = np.linalg.inv(B) @ v

# Back to standard
v_back = B @ v_new_basis

print("Coordinates in new basis:", v_new_basis)
print("Back to standard:", v_back)


Coordinates in new basis: [ 4.33333333 -0.66666667]
Back to standard: [5. 3.]


In [71]:
#Gram-Schmidt Process in Python (5×5 Matrix)
import numpy as np

# Step 1: Create a 5x5 matrix with linearly independent columns
A = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 1, 0, 1],
    [0, 1, 1, 0, 1],
    [0, 0, 1, 0, 1],
    [0, 0, 0, 1, 1]
], dtype=float)

print("Original matrix A:\n", A)

# Step 2: Initialize an empty Q matrix (same shape as A)
Q = np.zeros_like(A)

# Step 3: Gram-Schmidt process
for i in range(A.shape[1]):
    # Start with the current column of A
    v = A[:, i]
    
    # Subtract projections onto previous q_j
    for j in range(i):
        proj = np.dot(Q[:, j], A[:, i]) * Q[:, j]
        v = v - proj
    
    # Normalize the vector
    norm = np.linalg.norm(v)
    if norm == 0:
        raise ValueError("Vectors are linearly dependent.")
    Q[:, i] = v / norm

    # Print each step
    print(f"\nStep {i+1}:")
    print("Orthogonal vector (before normalization):", v)
    print("Normalized q_{}:".format(i+1), Q[:, i])

# Step 4: Verify QᵀQ = I
print("\nQ matrix:\n", Q)
print("\nQᵀQ (should be Identity):\n", np.round(Q.T @ Q, 4))


Original matrix A:
 [[1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 1.]
 [0. 1. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1.]]

Step 1:
Orthogonal vector (before normalization): [1. 1. 0. 0. 0.]
Normalized q_1: [0.70710678 0.70710678 0.         0.         0.        ]

Step 2:
Orthogonal vector (before normalization): [ 0.5 -0.5  1.   0.   0. ]
Normalized q_2: [ 0.40824829 -0.40824829  0.81649658  0.          0.        ]

Step 3:
Orthogonal vector (before normalization): [-0.33333333  0.33333333  0.33333333  1.          0.        ]
Normalized q_3: [-0.28867513  0.28867513  0.28867513  0.8660254   0.        ]

Step 4:
Orthogonal vector (before normalization): [ 0.25 -0.25 -0.25  0.25  1.  ]
Normalized q_4: [ 0.2236068  -0.2236068  -0.2236068   0.2236068   0.89442719]

Step 5:
Orthogonal vector (before normalization): [-0.2  0.2  0.2 -0.2  0.2]
Normalized q_5: [-0.4472136  0.4472136  0.4472136 -0.4472136  0.4472136]

Q matrix:
 [[ 0.70710678  0.40824829 -0.28867513  0.2236068  -0.4472136 ]
 [ 0.70710678 

In [73]:

# Vectors
v1 = np.array([3, 1])
v2 = np.array([2, 2])

# Step 1: Normalize v1
q1 = v1 / np.linalg.norm(v1)

# Step 2: Projection of v2 onto q1
proj = np.dot(v2, q1) * q1
u2 = v2 - proj
q2 = u2 / np.linalg.norm(u2)

print("q1 =", q1)
print("q2 =", q2)


q1 = [0.9486833  0.31622777]
q2 = [-0.31622777  0.9486833 ]


In [75]:
#Eigenvalues and Eigenvectors

A = np.array([[2, 1],
              [1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors (columns):\n", eigenvectors)


Eigenvalues: [3. 1.]
Eigenvectors (columns):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [77]:
#page rank
# Link matrix
L = np.array([
    [0,   0,   1],
    [0.5, 0,   0],
    [0.5, 1,   0]
])

# Damping factor
d = 0.85
N = L.shape[0]
A = d * L + (1 - d) / N * np.ones((N, N))

# Initialize rank vector
R = np.ones(N) / N

# Power iteration
for i in range(100):
    R = A @ R

print("PageRank:", np.round(R, 4))


PageRank: [0.3878 0.2148 0.3974]
